apiVersion: v1
kind: Service
metadata:
  name: kafka-3
  namespace: dc1
spec:
  selector:
    app: kafka-3
  ports:
    - name: client
      protocol: TCP
      port: 9092
      targetPort: 9092

---
apiVersion: v1
kind: Pod
metadata:
  name: kafka-3
  namespace: dc1
  labels:
    app: kafka-3
spec:
  containers:
  - name: kafka-3
    image: confluentinc/cp-kafka:6.0.0
    resources:
      limits:
        memory: "1000Mi"
      requests:
        memory: "1000Mi"
    env:
    - name: KAFKA_ZOOKEEPER_CONNECT
      value: zookeeper-1:2181,zookeeper-2:2181,zookeeper-3:2181
    - name: KAFKA_BROKER_ID
      value: "3"
    - name: KAFKA_ADVERTISED_LISTENERS
      value: PLAINTEXT://kafka-3:9092
